### ISSUE TITLE
Pitch and Co. 

### ISSUE THREAD

**Issue by Toybulldog** [ch-nry/VCV_nozori#15] opened 2020-09-21 07:05 UTC
Hallo
In the video I show how I deal with Nozoid modules . There are constant crash or sound problems here and there. At the moment, when I open the Pitch, the system crashes every now and then. I have to duplicate the Pitch Module and then reconnect it so that it works again. Please watch the video completely so that you can see it, for me it is difficult to put it into words.

[Crash Nozoid.zip](https://github.com/ch-nry/VCV_nozori/files/5253780/Crash.Nozoid.zip)

https://youtu.be/UlhxlIi80XU
https://youtu.be/FQGyYyiyGW4

Lg Peter

**Comment by ch-nry** [comment] 2020-09-21 07:39
Hello,
I'm sorry so experience so many crash. Nozori module where developed for a specific hardware, I did not really use the software version. 
Thanks for the details bug report, it's lot's easier for me to debug.
According to the log, the 2 crash of the 1st video are caused by the LFO, not the pitch modules. 
From what I see at the end of the 1st video, it's probable that you are still experimenting initialisation error that was the cause of your previous bug report. I thought I solve them all... I'll have an other look as soon as I can.

Cyrille

**Comment by ch-nry** [comment] 2020-09-25 12:20
It should be fixed with last commit
edit : version number is now : 1.1.9

**Closed as completed by ch-nry** 2020-09-25 12:20 UTC

**Comment by Toybulldog** [comment] 2020-11-23 09:04
Hallo Cyrille
I am sorry that I am only now thanking you.
The modules sound wonderful .
As far as I can tell, everything seems to be fine.
Thanks for your efforts.

Lg peter

**Comment by ch-nry** [comment] 2020-11-23 15:02
Thanks, It' never too late!
I'm glad to know everything is working fine, and that you like the sound

**Comment by Toybulldog** [comment] 2020-11-25 10:20
Hallo Cyrille

Here is a little demo
https://youtu.be/WkvqwyttXGg
Lg peter

**Comment by ch-nry** [comment] 2020-11-25 19:18
thanks for the demo, it's always nice to see what people are doing with my modules, and that my work is not useless!
