### ISSUE TITLE
KS nozoid bug ? VCV Rack

### ISSUE THREAD

**Issue by Toybulldog** [ch-nry/VCV_nozori#14] opened 2020-09-15 16:03 UTC
Hello
when I use the module nozori_68_KS and then save it, there are noises when I call up the file again. If I duplicate the module it works again .

https://youtu.be/5h0T32ldvQk
MfG peter

**Comment by ch-nry** [comment] 2020-09-15 16:26
I thinks is because the delay line is not initialized. There is not need to in the hardware version. The fix is easy, but I'll have to fork the code between the rack version and the hardware version.
(initialisation problem may also be the cause of your other bug report)
thanks for the report, i'll fix it as soon as I can
best
Cyrille

**Comment by ch-nry** [comment] 2020-09-15 19:40
should be fixed with version 1.1.8

**Closed as completed by ch-nry** 2020-09-15 19:40 UTC

**Comment by Toybulldog** [comment] 2020-09-17 12:29
Thank you very much, I'm already looking forward to the update .
MfG peter

**Comment by ch-nry** [comment] 2020-09-20 11:03
I'm glad you like my modules. Thanks for the bug report, the new version should be available. Don't hesitate to tell me if you find other problems.
best
Cyrille // Nozoïd
